---
- hosts: all
  become: true
  tasks:
    - name: Обновление кэша пакетов
      apt:
        update_cache: yes

    - name: Установка mc, vim, htop, nmon
      apt:
        name:
          - mc
          - vim
          - htop
          - nmon
          - docker.io
          - net-tools
          - plocate
          - curl
        state: present

    - name: Установка Java
      apt:
        name: default-jre
        state: present

    - name: Установка Python 3 и pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Проверка установки Python
      command: python3 --version

    - name: Проверка установки pip
      command: pip3 --version